apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: udagram-api-user
        image: mendyslam/udagram-api-user:v1
        resources:
          requests:
            memory: "1500Mi"
            cpu: "0.5"
          limits:
            memory: "2500Mi"
            cpu: "1"
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: aws-secret
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-config
